# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='model_pic',
            field=models.ImageField(default='user_images/none/no-img.jpg', upload_to='user_images/'),
        ),
    ]
