# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20171204_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
