# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
