# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-10 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20171209_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='business', max_length=30),
            preserve_default=False,
        ),
    ]
